name: flutter_icons_catalog
description: "A Flutter plugin which stores String-IconData mapping and conversion methods."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_icons_catalog
        pluginClass: FlutterIconsCatalogPlugin
      ios:
        pluginClass: FlutterIconsCatalogPlugin

